### ISSUE TITLE
Error when building Rcs with bullet

### ISSUE THREAD

**Issue by Jihong-Zhu** [HRI-EU/Rcs#30]
Dear Michael,

I was having some problems with building Rcs with bullet. I am on 64bit Ubuntu 16.04.
I installed bullet from 
https://github.com/bulletphysics/bullet3
When I tried to build Rcs with bullet option ON, at first it was not able to find the header file so I added in the CMakeLists:
include_directories(/usr/local/include/bullet)

Then it seems it cannot link the .so files, the error was:
No rule to make target '/libLinearMath.so', needed by 'lib/libRcsPhysics.so'.

Do you have an idea of how to get around this?

Thanks a lot.

**Comment by famura** [comment]
Hi Jihong-Zhu,

I once struggled at the same point. Note that the repository you mentioned installs Bullet 3, whereas Rcs runs with 2.8.x. There are flags to change this during compiling. However, I in the end resorted to installing the Bullet library via `sudo apt-get install`. You may want to have a look at the `required_packages` variable [here](https://github.com/famura/SimuRLacra/blob/master/setup_deps.py).

Hope this helps,
Fabio

**Comment by mgienger** [comment]
I hope the comment helped to fix your issue, please let us know otherwise.
